-- Second wave of the polished block set: many more ready-made sections so
-- non-coders have real variety in "Add Block +". All render through the
-- theme-aware px-* renderers (see blockRenderers.js). Includes a few
-- data-only "variations" (same renderer, different starter content) at the
-- end. `html` is always derived client-side from default_fields.
--
-- Safe to re-run: ON CONFLICT DO NOTHING.

insert into nexus_block_catalog (id, org_id, block_type, name, category, description, default_fields, sort_order) values
  ('hero-centered', null, 'hero-centered', 'Centered Hero', 'Content', 'Big centered headline, subtext, two CTAs, and an image below.', '{"headings":["Everything you need, in one place"],"text":["A clear, benefit-led subheadline that tells visitors what you do in a single sentence."],"links":[{"href":"#","label":"Get started"},{"href":"#","label":"See how it works"}],"images":[{"src":"https://placehold.co/1000x560?text=Product","alt":"Product screenshot"}]}'::jsonb, 33),
  ('announcement', null, 'announcement', 'Announcement Bar', 'Structure', 'A thin full-width bar for promos or notices, with a link.', '{"text":["Launch week — 20% off all plans."],"links":[{"href":"#","label":"Claim offer"}]}'::jsonb, 34),
  ('checklist', null, 'checklist', 'Checklist', 'Content', 'A two-column list of benefits with checkmarks.', '{"headings":["What is included"],"items":[{"heading":"Unlimited pages","body":"Build as much as you need."},{"heading":"Custom domain","body":"Bring your own URL."},{"heading":"Fast hosting","body":"Global edge delivery."},{"heading":"No code required","body":"Drag, drop, publish."}]}'::jsonb, 35),
  ('feature-rows', null, 'feature-rows', 'Feature Rows', 'Content', 'Alternating image + text rows (zigzag) for walking through features.', '{"items":[{"heading":"Design without limits","body":"Compose pages from ready-made sections and make them yours.","image":"https://placehold.co/640x480?text=Design"},{"heading":"Publish in a click","body":"Go live instantly with fast, secure hosting.","image":"https://placehold.co/640x480?text=Publish"}]}'::jsonb, 36),
  ('metric-cards', null, 'metric-cards', 'Metric Cards', 'Social Proof', 'KPI cards: a big number, a label, and an optional note.', '{"headings":["The numbers"],"items":[{"heading":"10k+","body":"Active users","meta":"and growing"},{"heading":"99.9%","body":"Uptime","meta":"last 12 months"},{"heading":"4.9/5","body":"Average rating","meta":"across 1,200 reviews"}]}'::jsonb, 37),
  ('pricing-cards', null, 'pricing-cards', 'Pricing Cards', 'Conversion', 'Polished pricing plans with a highlighted "most popular" card.', '{"headings":["Simple, honest pricing"],"text":["Pick a plan that grows with you."],"plans":[{"name":"Starter","price":"$0","period":"/mo","features":["1 site","Community support"],"ctaLabel":"Start free","ctaHref":"#","highlighted":false},{"name":"Pro","price":"$29","period":"/mo","features":["Unlimited sites","Custom domain","Priority support"],"ctaLabel":"Go Pro","ctaHref":"#","highlighted":true},{"name":"Team","price":"$79","period":"/mo","features":["Everything in Pro","5 seats","Roles & permissions"],"ctaLabel":"Choose Team","ctaHref":"#","highlighted":false}]}'::jsonb, 38),
  ('testimonial-grid', null, 'testimonial-grid', 'Testimonial Grid', 'Social Proof', 'A grid of review cards with stars, avatar, name, and role.', '{"headings":["Loved by teams everywhere"],"items":[{"heading":"Jamie R.","meta":"Founder, Northwind","body":"We shipped our new site in a weekend. It just works.","image":"https://placehold.co/80x80?text=JR"},{"heading":"Priya S.","meta":"Marketing, Brightline","body":"The block library saved us weeks of design time.","image":"https://placehold.co/80x80?text=PS"},{"heading":"Marcus L.","meta":"Owner, The Copper Table","body":"Finally a builder my whole team can use.","image":"https://placehold.co/80x80?text=ML"}]}'::jsonb, 39),
  ('team-grid', null, 'team-grid', 'Team Grid', 'Social Proof', 'Photo cards for your team: portrait, name, role, and a short bio.', '{"headings":["Meet the team"],"items":[{"heading":"Alex Rivera","meta":"Founder","body":"Sets the vision.","image":"https://placehold.co/300x300?text=AR"},{"heading":"Priya Shah","meta":"Design Lead","body":"Makes it beautiful.","image":"https://placehold.co/300x300?text=PS"},{"heading":"Sam Lee","meta":"Engineering","body":"Makes it fast.","image":"https://placehold.co/300x300?text=SL"}]}'::jsonb, 40),
  ('faq-accordion', null, 'faq-accordion', 'FAQ Accordion', 'Interactive', 'Click-to-expand questions with a +/- indicator (no JavaScript).', '{"headings":["Frequently asked questions"],"items":[{"heading":"Do I need to know how to code?","body":"Not at all — everything is drag-and-drop with ready-made blocks."},{"heading":"Can I use my own domain?","body":"Yes, connect any custom domain from settings."},{"heading":"Is there a free plan?","body":"Yes, start free and upgrade whenever you are ready."}]}'::jsonb, 41),
  ('contact-split', null, 'contact-split', 'Contact + Form', 'Conversion', 'Contact details on the left, a working contact form on the right.', '{"headings":["Get in touch"],"text":["We usually reply within one business day."],"links":[{"href":"mailto:hello@example.com","label":"hello@example.com"},{"href":"tel:+15551234567","label":"(555) 123-4567"}]}'::jsonb, 42),
  ('gallery-masonry', null, 'gallery-masonry', 'Masonry Gallery', 'Media', 'A Pinterest-style masonry grid of images.', '{"headings":["Gallery"],"images":[{"src":"https://placehold.co/500x700?text=1","alt":"1"},{"src":"https://placehold.co/500x400?text=2","alt":"2"},{"src":"https://placehold.co/500x600?text=3","alt":"3"},{"src":"https://placehold.co/500x450?text=4","alt":"4"},{"src":"https://placehold.co/500x650?text=5","alt":"5"},{"src":"https://placehold.co/500x400?text=6","alt":"6"}]}'::jsonb, 43),
  ('cta-split', null, 'cta-split', 'CTA Split', 'Conversion', 'A soft banner with a heading + text on the left and a button on the right.', '{"headings":["Ready to build?"],"text":["Launch your site today — no credit card required."],"links":[{"href":"#","label":"Get started"}]}'::jsonb, 44),
  ('blog-cards', null, 'blog-cards', 'Blog Cards', 'Content', 'Article cards with image, category, title, excerpt, and a read link.', '{"headings":["From the blog"],"items":[{"heading":"5 tips for a faster site","meta":"Guides","body":"Small changes that make a big difference to load times.","image":"https://placehold.co/480x270?text=Post+1","link":"#"},{"heading":"Designing with blocks","meta":"Design","body":"How to compose pages that look custom-built.","image":"https://placehold.co/480x270?text=Post+2","link":"#"},{"heading":"Launch checklist","meta":"Product","body":"Everything to check before you go live.","image":"https://placehold.co/480x270?text=Post+3","link":"#"}]}'::jsonb, 45),
  ('banner-image', null, 'banner-image', 'Image Banner', 'Media', 'A full-bleed image with an overlay heading, text, and CTA.', '{"headings":["Made for moments that matter"],"text":["A short, evocative line over a full-bleed image."],"images":[{"src":"https://placehold.co/1200x500?text=Banner","alt":"Banner"}],"links":[{"href":"#","label":"Explore"}]}'::jsonb, 46),
  -- Variations (same renderer, different starter content)
  ('hero-split-product', null, 'hero-split', 'Split Hero — Product', 'Content', 'Split hero framed for a product or app launch.', '{"headings":["Ship your site this weekend"],"text":["Everything you need to design, build, and launch — without a developer."],"links":[{"href":"#","label":"Start free"},{"href":"#","label":"Watch demo"}],"images":[{"src":"https://placehold.co/800x600?text=App","alt":"App"}]}'::jsonb, 47),
  ('feature-icons-4up', null, 'feature-icons', 'Feature Tiles — 4 up', 'Content', 'Four compact feature tiles.', '{"headings":["Why teams choose us"],"items":[{"heading":"Fast","body":"Lightning quick."},{"heading":"Secure","body":"Safe by default."},{"heading":"Flexible","body":"Built your way."},{"heading":"Supported","body":"We have got you."}]}'::jsonb, 48),
  ('card-grid-2up', null, 'card-grid', 'Card Grid — 2 up', 'Content', 'A two-column card grid for a pair of highlights.', '{"headings":["Highlights"],"items":[{"heading":"For creators","body":"Portfolios that stand out.","image":"https://placehold.co/400x240?text=A","link":"#"},{"heading":"For businesses","body":"Sites that convert.","image":"https://placehold.co/400x240?text=B","link":"#"}]}'::jsonb, 49),
  ('checklist-reasons', null, 'checklist', 'Checklist — Reasons', 'Content', 'A compact reasons-to-choose checklist.', '{"headings":["Why switch"],"items":[{"heading":"No lock-in"},{"heading":"Free to start"},{"heading":"Fast support"},{"heading":"Cancel anytime"}]}'::jsonb, 50)
on conflict (id) do nothing;
